config/routes.rb
Rails.application.routes.draw do
  resources :destinations

  resources :homes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/destination.rb
class DestinationRecord < ApplicationRecord
end

app/models/home.rb
class HomeRecord < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController

def index
  pizza = nil
  login = RestClient::Request.new({
    method: :post,
    url: 'localhost:3000/auth/login?email=sam@sam.sam&password=123456'
  }).execute do |soon_to_be_a_token, request, result|
      case soon_to_be_a_token.code
      when 400
        [ :error, JSON.parse(soon_to_be_a_token.to_str) ]
      when 200
        [ :success, JSON.parse(soon_to_be_a_token.to_str) ]
        puts request.headers
      else
        fail "Invalid soon_to_be_a_token #{soon_to_be_a_token.to_str} received."
      end
      pizza = soon_to_be_a_token
    end

    token = JSON.parse(pizza)

  response = RestClient::Request.execute(
    method: :get,
    url: 'localhost:3000/destinations/',
    headers: { Authorization: token["token"] }
  )

@destinations = JSON.parse(response)


 end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/destinations/index.html.erb
<% if @destinations.any? %>

  <% @destinations.each do |destination| %>
    <ul>
      <li><%= destination["destination"] %></li>
    </ul>
  <% end %>

<% else %>
  <p>You are a failure. Try again.</p>
<% end %>

<p><%= @token %></p>

app/views/homes/index.html.erb
<h1>This is a page</h1>

<%= link_to "destinations", destinations_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApiCaller</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>